meal_1 = Meal.create(name: "Filet Mignon with  Asparagus", calorie_count: 900) 
# meal_2 = Meal.create(name: "Quinoa with Spinach", calorie_count: 400)
# meal_3 = Meal.create(name: "Chickpeas with Kale", calorie_count: 300)
# meal_4 = Meal.create(name: "Chicken with Iceburg Lettuce", calorie_count: 700)
# meal_5 = Meal.create(name: "Salmon with Roasted Peppers", calorie_count: 500)



ingridients_1 = Ingredient.create(name: "Filet Mignon", meal_id: meal_1.id)
# ingridients_2 = Ingredient.create(name: "Figs")
# ingridients_3 = Ingredient.create(name = "Twink)ies")
# ingridients_4 = Ingredient.create(name = "BBQ chips)")
# ingridients_5 = Ingredient.create(name = "Mustard")
# ingridients_6 = Ingredient.create(name = "Mashed Potatoes")
# ingridients_7 = Ingredient.create(name = "Scallions")
# ingridients_8 = Ingredient.create(name = "Asparagus")
# ingridients_9 = Ingredient.create(name = "Quinoa")
# ingridients_10 = Ingredient.create (name = "Black Rice")
# ingridients_11 = Ingredient.create (name = "Salmon")
# ingridients_12 = Ingredient.create (name = "Turkey")
# ingridients_13 = Ingredient.create (name = "Ben and Jerrys Ice Cream")
# ingridients_14 = Ingredient.create (name = "Jolly Ranchers")
# ingridients_15 = Ingredient.create (name = "Sweet Potatoes")
# ingridients_16 = Ingredient.create (name = "Spinach")
# ingridients_17 = Ingredient.create (name = "Cucumbers")
# ingridients_18 = Ingredient.create (name = "Watermelon")
# ingridients_19 = Ingredient.create (name = "Brown Rice")
# ingridients_20 = Ingredient.create (name = "Kale")
# ingridients_21 = Ingredient.create (name = "Roasted Peppers")
# ingridients_22 = Ingredient.create (name = "Chicken")
# ingridients_23 = Ingredient.create (name = "Lollipops")
# ingridients_24 = Ingredient.create (name = "Iceburg Lettuce")
# ingridients_25 = Ingredient.create (name = "Kit Kat")
# ingridients_26 = Ingredient.create (name = "White Rice")
# ingridients_27 = Ingredient.create (name = "Lentils")
# ingridients_28 = Ingredient.create (name = "Avocado")
# ingridients_29 = Ingredient.create (name = "Chocolate covered bacon bits")
# ingridients_30 = Ingredient.create (name = "Apples")


