Meal.destroy_all
Ingredient.destroy_all 

meal_1 = Meal.create(name: "Filet Mignon with  Asparagus", calorie_count: 900) 
meal_2 = Meal.create(name: "Quinoa with Spinach", calorie_count: 400)
meal_3 = Meal.create(name: "Chickpeas with Kale", calorie_count: 300)
meal_4 = Meal.create(name: "Chicken with Iceburg Lettuce", calorie_count: 700)
meal_5 = Meal.create(name: "Salmon with Roasted Peppers", calorie_count: 500)



ingredients_1 = Ingredient.create(name: "Filet Mignon", meal_id: meal_1.id)
ingredients_2 = Ingredient.create(name: "Figs")
ingredients_3 = Ingredient.create(name: "Twinkies")
ingredients_4 = Ingredient.create(name: "Chickpeas", meal_id: meal_3.id)
ingredients_5 = Ingredient.create(name: "Mustard")
ingredients_6 = Ingredient.create(name: "Mashed Potatoes", meal_id: meal_1.id)
ingredients_7 = Ingredient.create(name: "Scallions")
ingredients_8 = Ingredient.create(name: "Asparagus", meal_id: meal_1.id)
ingredients_9 = Ingredient.create(name: "Quinoa", meal_id: meal_2.id)
ingredients_10 = Ingredient.create(name:"Black Rice", meal_id: meal_2.id)
ingredients_11 = Ingredient.create(name: "Salmon", meal_id: meal_5.id)
ingredients_12 = Ingredient.create(name: "Turkey")
ingredients_13 = Ingredient.create(name: "Ben and Jerrys Ice Cream")
ingredients_14 = Ingredient.create(name: "Jolly Ranchers")
ingredients_15 = Ingredient.create(name: "Sweet Potatoes")
ingredients_16 = Ingredient.create(name: "Spinach", meal_id: meal_2.id)
ingredients_17 = Ingredient.create(name: "Cucumbers")
ingredients_18 = Ingredient.create(name: "Watermelon")
ingredients_19 = Ingredient.create(name: "Brown Rice", meal_id: meal_4.id)
ingredients_20 = Ingredient.create(name: "Kale", meal_id: meal_3.id)
ingredients_21 = Ingredient.create(name: "Roasted Peppers", meal_id: meal_5.id)
ingredients_22 = Ingredient.create(name: "Chicken", meal_id: meal_4.id)
ingredients_23 = Ingredient.create(name: "Lollipops")
ingredients_24 = Ingredient.create(name: "Iceburg Lettuce", meal_id: meal_4.id)
ingredients_25 = Ingredient.create(name: "Kit Kat")
ingredients_26 = Ingredient.create(name: "White Rice", meal_id: meal_5.id)
ingredients_27 = Ingredient.create(name: "Lentils", meal_id: meal_3.id)
ingredients_28 = Ingredient.create(name: "Avocado")
ingredients_29 = Ingredient.create(name: "Chocolate covered bacon bits")
ingredients_30 = Ingredient.create(name: "Apples")